### ISSUE TITLE
How to add a new pkg

### ISSUE THREAD

**Issue by lemmyg** [AdityaGarg8/t2-ubuntu-repo#2]
Hello @AdityaGarg8 ,
When you have spare time, could you please explain me what the process to add new pkg version.
Thanks

**Comment by AdityaGarg8** [comment]
1. Push the new/updated .deb to the repo
2. Run the github action to sign the package.

**Comment by lemmyg** [comment]
done thanks

**Comment by AdityaGarg8** [comment]
In case the new packages are getting installed using the repo, you may close this issue.

**Comment by AdityaGarg8** [comment]
pages-build deployment just publishes the GitHub repo to the URL being used as an apt repo.

It doesn't sign the package. Whenever I push any package, I push them after signing the repo at my end since I have private gpg key, that is required to sign these packages.

Since you do not have my private gpg key, I have put a workaround by making this small CI so that you are also able to sigh the packages using my key.
